'use client'

import React, { useState, useEffect } from 'react'
import Link from 'next/link'
import { 
  GraduationCap, Shield, Brain, MapPin, Star, Clock, MessageSquare, 
  CheckCircle2, Users, BookOpen, Award, TrendingUp, Sparkles, 
  ArrowRight, ChevronDown, Play, Search, Calendar, CreditCard,
  Video, Bot, Target, BarChart3, Heart, Menu, X, Moon, Sun,
  ShieldCheck, Zap, Globe, Lock
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { demoPlatformStats } from '@/lib/demo-data'

export default function LandingPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [isDark, setIsDark] = useState(false)
  const [scrolled, setScrolled] = useState(false)

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20)
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  useEffect(() => {
    if (isDark) {
      document.documentElement.classList.add('dark')
    } else {
      document.documentElement.classList.remove('dark')
    }
  }, [isDark])

  const stats = [
    { value: `${(demoPlatformStats.total_tutors / 1000).toFixed(1)}K+`, label: 'Verified Tutors', icon: GraduationCap },
    { value: `${(demoPlatformStats.total_students / 1000).toFixed(1)}K+`, label: 'Happy Students', icon: Users },
    { value: `${demoPlatformStats.total_subjects}+`, label: 'Subjects', icon: BookOpen },
    { value: `${(demoPlatformStats.total_sessions / 1000).toFixed(1)}K+`, label: 'Sessions Completed', icon: Clock },
  ]

  const howItWorks = [
    { step: '01', title: 'Create Your Profile', desc: 'Tell us about your learning needs, subjects, goals, and preferences.', icon: Users, color: 'from-blue-500 to-indigo-600' },
    { step: '02', title: 'AI Finds Your Match', desc: 'Our AI analyzes 20+ factors to recommend the best tutors for you.', icon: Brain, color: 'from-purple-500 to-pink-600' },
    { step: '03', title: 'Connect & Schedule', desc: 'Chat with tutors, watch intro videos, and book your first session.', icon: Calendar, color: 'from-emerald-500 to-teal-600' },
    { step: '04', title: 'Learn & Grow', desc: 'Track progress with AI-powered insights and personalized study plans.', icon: TrendingUp, color: 'from-amber-500 to-orange-600' },
  ]

  const features = [
    { title: 'AI Tutor Matching', desc: 'Our AI analyzes learning style, goals, budget, location, and 20+ factors to find your perfect tutor match.', icon: Sparkles, gradient: 'from-indigo-500 to-purple-600' },
    { title: 'Verified & Trusted', desc: 'Every tutor undergoes identity, education, and background verification. Verified badges you can trust.', icon: ShieldCheck, gradient: 'from-emerald-500 to-green-600' },
    { title: 'Safe Sessions', desc: 'Real-time session tracking, SOS alerts, safe messaging, and parent visibility for every in-person session.', icon: Shield, gradient: 'from-red-500 to-rose-600' },
    { title: 'AI Study Plans', desc: 'Personalized 4-week study roadmaps generated by AI based on your current level and target goals.', icon: Target, gradient: 'from-blue-500 to-cyan-600' },
    { title: 'AI Assistant', desc: 'Chat with our AI assistant for tutor recommendations, study tips, exam strategies, and learning guidance.', icon: Bot, gradient: 'from-violet-500 to-purple-600' },
    { title: 'Location Search', desc: 'Find tutors near you with our interactive map. See availability, ratings, and distance in real-time.', icon: MapPin, gradient: 'from-orange-500 to-red-500' },
    { title: 'Progress Tracking', desc: 'Visual dashboards showing grades, study hours, session history, and improvement analytics.', icon: BarChart3, gradient: 'from-teal-500 to-emerald-600' },
    { title: 'Secure Payments', desc: 'UPI, cards, wallets — all payments are secure with transparent pricing. No hidden fees.', icon: CreditCard, gradient: 'from-pink-500 to-rose-600' },
  ]

  const testimonials = [
    { name: 'Priya Sharma', role: 'Parent', rating: 5, text: 'The AI matching is incredible! It found a tutor who perfectly matched my son\'s visual learning style. His math grades went from B to A+ in just 3 months.', location: 'Bangalore' },
    { name: 'Dr. Arjun Mehta', role: 'Tutor', rating: 5, text: 'HomeTutor AI has transformed how I connect with students. The platform handles scheduling, payments, and even generates session summaries. I can focus entirely on teaching.', location: 'Bangalore' },
    { name: 'Rajesh Kumar', role: 'Parent', rating: 5, text: 'The safety features give me complete peace of mind. I can track sessions, see the tutor\'s location, and the SOS button is always there. Truly trustworthy.', location: 'Delhi' },
  ]

  const faqs = [
    { q: 'How does AI tutor matching work?', a: 'Our AI analyzes your child\'s learning style, subjects, goals, budget, location, and 20+ other factors to recommend the most compatible tutors. Each recommendation comes with a detailed compatibility score and explanation.' },
    { q: 'How are tutors verified?', a: 'Every tutor undergoes a multi-step verification: email, phone, identity (government ID), education certificates, and optional certifications. Tutors must also submit an introduction video and receive admin approval.' },
    { q: 'What safety features are available?', a: 'We provide real-time session tracking, SOS emergency alerts, safe in-app messaging, location sharing with parents, session checklists, and a dedicated safety center. Parents can monitor sessions in real-time.' },
    { q: 'How do payments work?', a: 'We support UPI, credit/debit cards, net banking, and wallets through Razorpay. Pricing is transparent — you see the session price and platform fee upfront. Tutors receive payment after session completion.' },
    { q: 'Can I try a tutor before committing?', a: 'Yes! You can book a trial session at a reduced rate to experience the tutor\'s teaching style before committing to regular sessions.' },
    { q: 'Is online tutoring available?', a: 'Absolutely! Tutors can offer online sessions via our built-in video calling, in-person sessions, or both. You can filter by availability and mode.' },
  ]

  return (
    <div className="min-h-screen bg-[var(--background)]">
      {/* Navigation */}
      <nav className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${scrolled ? 'bg-[var(--background)]/95 backdrop-blur-xl shadow-sm border-b border-[var(--border)]' : 'bg-transparent'}`}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
                <GraduationCap className="w-5 h-5 text-white" />
              </div>
              <span className="font-bold text-lg">HomeTutor <span className="text-[var(--primary)]">AI</span></span>
            </Link>

            <div className="hidden lg:flex items-center gap-1">
              {[
                { href: '/', label: 'Home' },
                { href: '/tutors', label: 'Find Tutors' },
                { href: '/map', label: 'Map' },
                { href: '/safety', label: 'Safety' },
                { href: '/how-it-works', label: 'How It Works' },
              ].map(link => (
                <Link key={link.href} href={link.href} className="px-3 py-2 text-sm font-medium text-[var(--muted-foreground)] hover:text-[var(--foreground)] transition-colors rounded-lg hover:bg-[var(--secondary)]">
                  {link.label}
                </Link>
              ))}
            </div>

            <div className="hidden lg:flex items-center gap-3">
              <button onClick={() => setIsDark(!isDark)} className="p-2 rounded-lg hover:bg-[var(--secondary)] transition-colors" aria-label="Toggle theme">
                {isDark ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
              </button>
              <Link href="/login">
                <Button variant="ghost" size="sm">Log In</Button>
              </Link>
              <Link href="/register">
                <Button size="sm" className="bg-gradient-to-r from-indigo-500 to-purple-600 text-white border-0">Get Started</Button>
              </Link>
            </div>

            <button className="lg:hidden p-2" onClick={() => setMobileMenuOpen(!mobileMenuOpen)} aria-label="Toggle menu">
              {mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </button>
          </div>
        </div>

        {/* Mobile menu */}
        {mobileMenuOpen && (
          <div className="lg:hidden bg-[var(--background)] border-b border-[var(--border)] animate-fade-in">
            <div className="px-4 py-4 space-y-2">
              {['Find Tutors', 'Map', 'Safety', 'How It Works'].map(item => (
                <Link key={item} href={`/${item.toLowerCase().replace(/ /g, '-')}`} className="block px-3 py-2 rounded-lg text-sm hover:bg-[var(--secondary)]" onClick={() => setMobileMenuOpen(false)}>
                  {item}
                </Link>
              ))}
              <div className="pt-2 flex gap-2">
                <Link href="/login" className="flex-1"><Button variant="outline" className="w-full" size="sm">Log In</Button></Link>
                <Link href="/register" className="flex-1"><Button className="w-full bg-gradient-to-r from-indigo-500 to-purple-600 text-white" size="sm">Get Started</Button></Link>
              </div>
            </div>
          </div>
        )}
      </nav>

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 lg:pt-40 lg:pb-32 overflow-hidden">
        {/* Background decoration */}
        <div className="absolute inset-0 -z-10">
          <div className="absolute top-20 left-10 w-72 h-72 bg-indigo-200/30 dark:bg-indigo-900/20 rounded-full blur-3xl" />
          <div className="absolute top-40 right-10 w-96 h-96 bg-purple-200/30 dark:bg-purple-900/20 rounded-full blur-3xl" />
          <div className="absolute bottom-20 left-1/3 w-80 h-80 bg-pink-200/20 dark:bg-pink-900/10 rounded-full blur-3xl" />
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="animate-fade-in">
              <Badge variant="secondary" className="mb-6 px-4 py-1.5 text-sm">
                <Sparkles className="w-3.5 h-3.5 mr-1.5" />
                AI-Powered Tutor Matching
              </Badge>
              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold leading-tight tracking-tight mb-6">
                Find the Right Tutor.{' '}
                <span className="gradient-text">Build a Better Future.</span>
              </h1>
              <p className="text-lg text-[var(--muted-foreground)] mb-8 max-w-xl leading-relaxed">
                AI-powered tutor matching, verified tutors, secure communication, personalized study plans and real-time safety — all in one place.
              </p>
              <div className="flex flex-wrap gap-4">
                <Link href="/tutors">
                  <Button size="xl" className="bg-gradient-to-r from-indigo-500 to-purple-600 text-white border-0 shadow-lg shadow-indigo-500/25">
                    <Search className="w-4 h-4" />
                    Find a Tutor
                  </Button>
                </Link>
                <Link href="/register?role=tutor">
                  <Button size="xl" variant="outline">
                    <GraduationCap className="w-4 h-4" />
                    Become a Tutor
                  </Button>
                </Link>
              </div>
              <div className="mt-8 flex items-center gap-6 text-sm text-[var(--muted-foreground)]">
                <div className="flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4 text-emerald-500" /> Verified Tutors</div>
                <div className="flex items-center gap-1.5"><Shield className="w-4 h-4 text-blue-500" /> Safe & Secure</div>
                <div className="flex items-center gap-1.5"><Sparkles className="w-4 h-4 text-purple-500" /> AI-Powered</div>
              </div>
            </div>

            {/* Hero Dashboard Mockup */}
            <div className="relative animate-slide-up hidden lg:block">
              <div className="relative bg-[var(--card)] rounded-2xl border border-[var(--border)] shadow-2xl p-6 space-y-4">
                {/* Top bar */}
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-xs text-[var(--muted-foreground)]">Good Morning, Priya 👋</p>
                    <p className="font-semibold">Student Dashboard</p>
                  </div>
                  <Badge variant="success">
                    <Sparkles className="w-3 h-3 mr-1" /> AI Ready
                  </Badge>
                </div>

                {/* Stats row */}
                <div className="grid grid-cols-3 gap-3">
                  {[
                    { label: 'AI Match', value: '95%', color: 'text-indigo-600', bg: 'bg-indigo-50 dark:bg-indigo-900/30' },
                    { label: 'Sessions', value: '24', color: 'text-emerald-600', bg: 'bg-emerald-50 dark:bg-emerald-900/30' },
                    { label: 'Progress', value: '↑18%', color: 'text-purple-600', bg: 'bg-purple-50 dark:bg-purple-900/30' },
                  ].map(stat => (
                    <div key={stat.label} className={`${stat.bg} rounded-xl p-3 text-center`}>
                      <p className={`text-xl font-bold ${stat.color}`}>{stat.value}</p>
                      <p className="text-[10px] text-[var(--muted-foreground)] mt-0.5">{stat.label}</p>
                    </div>
                  ))}
                </div>

                {/* Tutor card preview */}
                <div className="flex items-center gap-3 p-3 rounded-xl bg-[var(--secondary)]">
                  <div className="w-12 h-12 rounded-full bg-gradient-to-br from-indigo-400 to-purple-500 flex items-center justify-center text-white font-bold">AM</div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <p className="font-medium text-sm">Dr. Arjun Mehta</p>
                      <CheckCircle2 className="w-3.5 h-3.5 text-blue-500" />
                    </div>
                    <p className="text-xs text-[var(--muted-foreground)]">Mathematics • 4.9⭐ • ₹800/hr</p>
                  </div>
                  <Badge className="bg-emerald-100 text-emerald-700 border-emerald-200 text-[10px]">92% Match</Badge>
                </div>

                {/* Safety status */}
                <div className="flex items-center justify-between p-3 rounded-xl border border-emerald-200 dark:border-emerald-800 bg-emerald-50/50 dark:bg-emerald-900/20">
                  <div className="flex items-center gap-2">
                    <Shield className="w-4 h-4 text-emerald-600" />
                    <span className="text-xs font-medium text-emerald-700 dark:text-emerald-400">All Safety Checks Passed</span>
                  </div>
                  <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                </div>

                {/* Calendar preview */}
                <div className="flex gap-2">
                  {['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].map((day, i) => (
                    <div key={day} className={`flex-1 text-center py-2 rounded-lg text-xs ${i === 2 ? 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300 font-semibold' : 'text-[var(--muted-foreground)]'}`}>
                      <p>{day}</p>
                      <p className="font-medium mt-1">{15 + i}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Floating badges */}
              <div className="absolute -top-4 -right-4 bg-[var(--card)] rounded-xl border border-[var(--border)] shadow-lg p-3 animate-bounce" style={{ animationDuration: '3s' }}>
                <div className="flex items-center gap-2">
                  <Brain className="w-5 h-5 text-purple-500" />
                  <div>
                    <p className="text-[10px] text-[var(--muted-foreground)]">AI Match Score</p>
                    <p className="font-bold text-sm text-purple-600">95%</p>
                  </div>
                </div>
              </div>
              <div className="absolute -bottom-4 -left-4 bg-[var(--card)] rounded-xl border border-[var(--border)] shadow-lg p-3">
                <div className="flex items-center gap-2">
                  <MapPin className="w-5 h-5 text-rose-500" />
                  <div>
                    <p className="text-[10px] text-[var(--muted-foreground)]">Tutors Nearby</p>
                    <p className="font-bold text-sm">12 within 5km</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="py-12 border-y border-[var(--border)] bg-[var(--secondary)]/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat) => (
              <div key={stat.label} className="text-center">
                <stat.icon className="w-6 h-6 mx-auto mb-2 text-[var(--primary)]" />
                <p className="text-3xl font-bold gradient-text">{stat.value}</p>
                <p className="text-sm text-[var(--muted-foreground)] mt-1">{stat.label}</p>
              </div>
            ))}
          </div>
          <p className="text-center text-xs text-[var(--muted-foreground)] mt-6 flex items-center justify-center gap-1">
            <span className="demo-banner text-[10px]">DEMO</span> Statistics shown are configurable demo data
          </p>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 lg:py-28" id="how-it-works">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4"><Zap className="w-3 h-3 mr-1" /> Simple Process</Badge>
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">How It Works</h2>
            <p className="text-[var(--muted-foreground)] max-w-2xl mx-auto">Get started in 4 simple steps. Our AI handles the complex matching so you can focus on learning.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {howItWorks.map((item) => (
              <Card key={item.step} className="premium-card relative overflow-hidden group">
                <CardContent className="p-6">
                  <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${item.color} flex items-center justify-center mb-4 transition-transform group-hover:scale-110`}>
                    <item.icon className="w-6 h-6 text-white" />
                  </div>
                  <p className="text-xs font-bold text-[var(--muted-foreground)] mb-2">STEP {item.step}</p>
                  <h3 className="font-semibold text-lg mb-2">{item.title}</h3>
                  <p className="text-sm text-[var(--muted-foreground)] leading-relaxed">{item.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-20 lg:py-28 bg-[var(--secondary)]/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4"><Sparkles className="w-3 h-3 mr-1" /> Platform Features</Badge>
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">Everything You Need to Learn Better</h2>
            <p className="text-[var(--muted-foreground)] max-w-2xl mx-auto">AI-powered matching, verified tutors, real-time safety, and personalized learning — a complete tutoring ecosystem.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((f) => (
              <Card key={f.title} className="premium-card group">
                <CardContent className="p-6">
                  <div className={`w-11 h-11 rounded-xl bg-gradient-to-br ${f.gradient} flex items-center justify-center mb-4 transition-transform group-hover:scale-110 group-hover:shadow-lg`}>
                    <f.icon className="w-5 h-5 text-white" />
                  </div>
                  <h3 className="font-semibold mb-2">{f.title}</h3>
                  <p className="text-sm text-[var(--muted-foreground)] leading-relaxed">{f.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* AI Matching Feature */}
      <section className="py-20 lg:py-28">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <Badge variant="secondary" className="mb-4"><Brain className="w-3 h-3 mr-1" /> AI Technology</Badge>
              <h2 className="text-3xl lg:text-4xl font-bold mb-4">AI That Understands Learning</h2>
              <p className="text-[var(--muted-foreground)] mb-8 leading-relaxed">
                Our AI doesn&apos;t just match by subject. It analyzes learning style, goals, teaching methodology compatibility, 
                budget, location, schedule, and 15+ other factors to find the tutor who truly fits your child.
              </p>
              <div className="space-y-4">
                {[
                  { label: 'Subject Compatibility', score: 95 },
                  { label: 'Learning Style Match', score: 88 },
                  { label: 'Schedule Alignment', score: 92 },
                  { label: 'Budget Fit', score: 85 },
                  { label: 'Location Proximity', score: 90 },
                ].map(item => (
                  <div key={item.label}>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="font-medium">{item.label}</span>
                      <span className="text-[var(--primary)] font-semibold">{item.score}%</span>
                    </div>
                    <div className="h-2 bg-[var(--secondary)] rounded-full overflow-hidden">
                      <div className="h-full bg-gradient-to-r from-indigo-500 to-purple-500 rounded-full transition-all duration-1000" style={{ width: `${item.score}%` }} />
                    </div>
                  </div>
                ))}
              </div>
              <p className="text-xs text-[var(--muted-foreground)] mt-4 italic">* AI compatibility estimate based on profile analysis</p>
            </div>
            <div className="relative">
              <div className="bg-[var(--card)] rounded-2xl border border-[var(--border)] shadow-xl p-6">
                <div className="flex items-center gap-2 mb-4">
                  <Sparkles className="w-5 h-5 text-purple-500" />
                  <h3 className="font-semibold">AI Match Analysis</h3>
                </div>
                <div className="bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-indigo-900/20 dark:to-purple-900/20 rounded-xl p-4 mb-4">
                  <p className="text-center mb-2 text-sm text-[var(--muted-foreground)]">Overall AI Compatibility</p>
                  <p className="text-5xl font-bold text-center gradient-text">92%</p>
                  <p className="text-center text-xs text-[var(--muted-foreground)] mt-1">AI compatibility estimate</p>
                </div>
                <div className="p-4 bg-[var(--secondary)] rounded-xl">
                  <p className="text-sm font-medium mb-2">Why this tutor?</p>
                  <p className="text-sm text-[var(--muted-foreground)] leading-relaxed">
                    &quot;This tutor teaches Class 10 Mathematics, uses visual explanations that match your child&apos;s learning style, 
                    is available during your preferred evening schedule, and fits within your budget range.&quot;
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Safety Section */}
      <section className="py-20 lg:py-28 bg-gradient-to-br from-emerald-50 to-teal-50 dark:from-emerald-900/10 dark:to-teal-900/10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="success" className="mb-4"><Shield className="w-3 h-3 mr-1" /> Safety First</Badge>
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">Your Child&apos;s Safety, Our Priority</h2>
            <p className="text-[var(--muted-foreground)] max-w-2xl mx-auto">Multi-layered safety system designed to give parents complete peace of mind during every tutoring session.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              { icon: ShieldCheck, title: 'Tutor Verification', desc: 'Identity, education, and background verification for every tutor. Look for the verified badge.' },
              { icon: MessageSquare, title: 'Safe Messaging', desc: 'Contact info protection, content monitoring, and reporting tools built into every conversation.' },
              { icon: MapPin, title: 'Session Tracking', desc: 'Real-time approximate location sharing during in-person sessions. Parents stay informed.' },
              { icon: Shield, title: 'SOS Alert', desc: 'One-tap emergency SOS button during any session. Instant alerts to parents and platform safety team.' },
              { icon: Lock, title: 'Privacy Protected', desc: 'No exact addresses shared. Approximate service areas only. All data encrypted and protected.' },
              { icon: Award, title: 'Safety Checklist', desc: 'Pre-session safety verification checklist ensures everything is in order before each session.' },
            ].map(item => (
              <Card key={item.title} className="premium-card border-emerald-100 dark:border-emerald-800/30">
                <CardContent className="p-6">
                  <item.icon className="w-8 h-8 text-emerald-600 mb-4" />
                  <h3 className="font-semibold mb-2">{item.title}</h3>
                  <p className="text-sm text-[var(--muted-foreground)] leading-relaxed">{item.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 lg:py-28">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4"><Heart className="w-3 h-3 mr-1" /> Testimonials</Badge>
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">Loved by Parents & Tutors</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((t) => (
              <Card key={t.name} className="premium-card">
                <CardContent className="p-6">
                  <div className="flex gap-1 mb-4">
                    {Array.from({ length: t.rating }).map((_, i) => (
                      <Star key={i} className="w-4 h-4 fill-amber-400 text-amber-400" />
                    ))}
                  </div>
                  <p className="text-sm text-[var(--muted-foreground)] leading-relaxed mb-4">&quot;{t.text}&quot;</p>
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-indigo-400 to-purple-500 flex items-center justify-center text-white text-sm font-bold">
                      {t.name.split(' ').map(n => n[0]).join('')}
                    </div>
                    <div>
                      <p className="font-medium text-sm">{t.name}</p>
                      <p className="text-xs text-[var(--muted-foreground)]">{t.role} • {t.location}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 lg:py-28 bg-[var(--secondary)]/30">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">FAQ</Badge>
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">Frequently Asked Questions</h2>
          </div>
          <div className="space-y-4">
            {faqs.map((faq, i) => (
              <FaqItem key={i} question={faq.q} answer={faq.a} />
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 lg:py-28">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="bg-gradient-to-br from-indigo-500 to-purple-600 rounded-3xl p-12 text-white relative overflow-hidden">
            <div className="absolute inset-0 bg-[url('data:image/svg+xml,%3Csvg%20width%3D%2260%22%20height%3D%2260%22%20viewBox%3D%220%200%2060%2060%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cg%20fill%3D%22none%22%20fill-rule%3D%22evenodd%22%3E%3Cg%20fill%3D%22%23ffffff%22%20fill-opacity%3D%220.05%22%3E%3Cpath%20d%3D%22M36%2034v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6%2034v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6%204V0H4v4H0v2h4v4h2V6h4V4H6z%22%2F%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E')] opacity-50" />
            <div className="relative">
              <h2 className="text-3xl lg:text-4xl font-bold mb-4">Ready to Find the Perfect Tutor?</h2>
              <p className="text-white/80 mb-8 max-w-xl mx-auto">Join thousands of parents who trust HomeTutor AI to provide safe, personalized, and effective tutoring.</p>
              <div className="flex flex-wrap gap-4 justify-center">
                <Link href="/register">
                  <Button size="xl" className="bg-white text-indigo-600 hover:bg-white/90 border-0 shadow-lg">
                    Get Started Free
                    <ArrowRight className="w-4 h-4" />
                  </Button>
                </Link>
                <Link href="/tutors">
                  <Button size="xl" variant="outline" className="border-white/30 text-white hover:bg-white/10">
                    Browse Tutors
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[var(--border)] py-12 bg-[var(--secondary)]/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-8">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
                  <GraduationCap className="w-4 h-4 text-white" />
                </div>
                <span className="font-bold">HomeTutor AI</span>
              </div>
              <p className="text-sm text-[var(--muted-foreground)]">Find the right tutor. Learn with confidence.</p>
            </div>
            <div>
              <h4 className="font-semibold mb-3 text-sm">Platform</h4>
              <div className="space-y-2">
                {['Find Tutors', 'Become a Tutor', 'How It Works', 'Pricing'].map(l => (
                  <Link key={l} href="#" className="block text-sm text-[var(--muted-foreground)] hover:text-[var(--foreground)]">{l}</Link>
                ))}
              </div>
            </div>
            <div>
              <h4 className="font-semibold mb-3 text-sm">Safety</h4>
              <div className="space-y-2">
                {['Safety Center', 'Verification', 'Privacy', 'Terms'].map(l => (
                  <Link key={l} href="#" className="block text-sm text-[var(--muted-foreground)] hover:text-[var(--foreground)]">{l}</Link>
                ))}
              </div>
            </div>
            <div>
              <h4 className="font-semibold mb-3 text-sm">Support</h4>
              <div className="space-y-2">
                {['Help Center', 'Contact Us', 'FAQ', 'Blog'].map(l => (
                  <Link key={l} href="#" className="block text-sm text-[var(--muted-foreground)] hover:text-[var(--foreground)]">{l}</Link>
                ))}
              </div>
            </div>
          </div>
          <div className="border-t border-[var(--border)] pt-8 flex flex-col sm:flex-row justify-between items-center gap-4">
            <p className="text-sm text-[var(--muted-foreground)]">© 2025 HomeTutor AI. All rights reserved.</p>
            <div className="flex items-center gap-2">
              <Badge variant="warning" className="text-[10px]">DEMO</Badge>
              <span className="text-xs text-[var(--muted-foreground)]">Hackathon Demo Mode Active</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

function FaqItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false)
  return (
    <div className="border border-[var(--border)] rounded-xl overflow-hidden">
      <button
        className="w-full flex items-center justify-between p-5 text-left hover:bg-[var(--secondary)]/50 transition-colors"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
      >
        <span className="font-medium pr-4">{question}</span>
        <ChevronDown className={`w-5 h-5 text-[var(--muted-foreground)] transition-transform flex-shrink-0 ${open ? 'rotate-180' : ''}`} />
      </button>
      {open && (
        <div className="px-5 pb-5 animate-fade-in">
          <p className="text-sm text-[var(--muted-foreground)] leading-relaxed">{answer}</p>
        </div>
      )}
    </div>
  )
}
