'use client'

import React, { useState } from 'react'
import { ClipboardList, Sparkles, BookOpen, Calendar, CheckCircle2, Plus } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'

export default function StudyPlansPage() {
  const [generating, setGenerating] = useState(false)
  const [plans, setPlans] = useState([
    {
      id: 'plan-1',
      title: 'Class 10 CBSE Math Board Prep Plan',
      subject: 'Mathematics',
      weeks: 4,
      progress: 65,
      goals: ['Master Quadratic Equations', 'Solve 10 Sample Papers', 'Formula Revision'],
      weekly_milestones: [
        { week: 1, topic: 'Real Numbers & Polynomials', status: 'completed' },
        { week: 2, topic: 'Quadratic Equations & AP', status: 'completed' },
        { week: 3, topic: 'Triangles & Coordinate Geometry', status: 'in_progress' },
        { week: 4, topic: 'Trigonometry & Statistics', status: 'pending' },
      ]
    },
    {
      id: 'plan-2',
      title: 'Physics Mechanics Mastery Plan',
      subject: 'Physics',
      weeks: 3,
      progress: 30,
      goals: ['Newton Laws of Motion', 'Work, Energy & Power', 'Numerical Problem Speed'],
      weekly_milestones: [
        { week: 1, topic: 'Vectors & Kinematics', status: 'completed' },
        { week: 2, topic: 'Laws of Motion & Friction', status: 'in_progress' },
        { week: 3, topic: 'Work & Energy Problems', status: 'pending' },
      ]
    }
  ])

  const handleGenerateNew = () => {
    setGenerating(true)
    setTimeout(() => {
      setPlans([
        {
          id: `plan-${Date.now()}`,
          title: 'AI Chemistry Revision Sprint',
          subject: 'Chemistry',
          weeks: 2,
          progress: 0,
          goals: ['Chemical Reactions', 'Periodic Table Trends', 'Organic Chemistry Basics'],
          weekly_milestones: [
            { week: 1, topic: 'Inorganic Chemistry & Equations', status: 'in_progress' },
            { week: 2, topic: 'Organic Reactions & Revision', status: 'pending' },
          ]
        },
        ...plans
      ])
      setGenerating(false)
    }, 1500)
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">AI Study Plans</h1>
          <p className="text-sm text-[var(--muted-foreground)]">Personalized curriculum roadmaps generated by HomeTutor AI</p>
        </div>
        <Button onClick={handleGenerateNew} disabled={generating} className="bg-gradient-to-r from-indigo-500 to-purple-600 text-white">
          <Sparkles className="w-4 h-4" /> {generating ? 'Generating Plan...' : 'Generate AI Study Plan'}
        </Button>
      </div>

      <div className="space-y-6">
        {plans.map(plan => (
          <Card key={plan.id} className="premium-card">
            <CardHeader className="flex-row items-start justify-between">
              <div>
                <div className="flex items-center gap-2">
                  <CardTitle className="text-lg">{plan.title}</CardTitle>
                  <Badge variant="outline">{plan.subject}</Badge>
                </div>
                <p className="text-xs text-[var(--muted-foreground)] mt-1">{plan.weeks}-Week Structured Roadmap</p>
              </div>
              <div className="text-right">
                <span className="text-2xl font-bold text-[var(--primary)]">{plan.progress}%</span>
                <p className="text-[10px] text-[var(--muted-foreground)]">Completion</p>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Progress bar */}
              <div className="h-2 bg-[var(--secondary)] rounded-full overflow-hidden">
                <div className="h-full bg-gradient-to-r from-indigo-500 to-purple-600 rounded-full" style={{ width: `${plan.progress}%` }} />
              </div>

              {/* Milestones */}
              <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-3">
                {plan.weekly_milestones.map(m => (
                  <div key={m.week} className={`p-3 rounded-xl border text-xs ${
                    m.status === 'completed' ? 'border-emerald-200 bg-emerald-50/50 dark:bg-emerald-900/10' :
                    m.status === 'in_progress' ? 'border-indigo-200 bg-indigo-50/50 dark:bg-indigo-900/10' : 'border-[var(--border)]'
                  }`}>
                    <div className="flex items-center justify-between mb-1">
                      <span className="font-semibold text-[var(--muted-foreground)]">Week {m.week}</span>
                      <CheckCircle2 className={`w-3.5 h-3.5 ${m.status === 'completed' ? 'text-emerald-500' : 'text-gray-300'}`} />
                    </div>
                    <p className="font-medium">{m.topic}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}
